spring:
  config:
    import:
      - datasource.yml
      - redis.yml
  application:
    name: fcfs-reservation
  profiles:
    default: local
    group:
      local:
        - local-seed
  threads:
    virtual:
      enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
